export const images = [
  "https://d2zr04sdvfux2y.cloudfront.net/test/304c876d36e642ef92fbb6617509d628-image.jpg",
  "https://d2zr04sdvfux2y.cloudfront.net/test/6df6d32553a14efd8d9a3dcee725651c-image.jpg",
  "https://d2zr04sdvfux2y.cloudfront.net/test/f49177fedd6542f58df38d0874e3c3dd-image.jpg",
];

export const demoProductData = {
  base_product: {
    id: 30,
    brand: {
      id: 25,
      name: "TwinFish",
      slug: "twinfish",
      is_active: true,
      is_featured: true,
    },
    category: {
      id: 28,
      name: "Groceries",
      slug: "groceries",
      translation: {},
    },
    sub_category: {
      id: 38,
      name: "Chocolates & Candy",
      slug: "chocolates-candy",
      logo: "https://d2zr04sdvfux2y.cloudfront.net/test/ecfe1b5be3364cb3a9a3f9905c4473cb-image.jpg",
      translation: {},
    },
    deleted_at: null,
    name: "Chocolate",
    slug: "chocolate-777E13",
    description:
      "<p>Chocolate is&nbsp;<strong>a food product made from the fruit of a cacao tree (Theobroma cacao)</strong>. Raw, unprocessed chocolate tastes bitter and dry, but chocolate that's been fermented, dried, and roasted, and had a bit of sugar and cream added to it, tastes divine.</p>",
    is_active: true,
    is_featured: true,
  },
  variant: {
    id: 48,
    name: "Nuts Crisp Candy with Mixed Flavors (500g)",
    slug: "nuts-crisp-candy-with-mixed-flavors-g-4B7A1F",
    stock_available: [
      {
        product_variant_id: 48,
        country_id: 4,
        stock_balance: 29,
      },
    ],
    images: [
      "https://d2zr04sdvfux2y.cloudfront.net/test/304c876d36e642ef92fbb6617509d628-image.jpg",
      "https://d2zr04sdvfux2y.cloudfront.net/test/6df6d32553a14efd8d9a3dcee725651c-image.jpg",
      "https://d2zr04sdvfux2y.cloudfront.net/test/f49177fedd6542f58df38d0874e3c3dd-image.jpg",
    ],
    sku: "0000004843",
    selling_price: 650,
    specifications: [],
    meta: {
      description:
        "Twinfish Nuts Crisp is made from organically sourced nuts and processed in a high-standard hygiene-maintained facility.</p>\n<p>This is sweets type chocolate &amp; candy, it is extremely delectable for eat, which are reasonable for elderly person, grown-up, kids, woman to keep feet.</p>\n<p>Ingredients: Peanuts, Glucose Syrup, Sugar, Flour, Salt, Vanilla, Palm oil, Artificial Flavor.</p>\n<ul>\n<li>Consisting of various nuts</li>\n<li>Great taste</li>\n<li>Super nut delicious</li>\n<li>Delicious crisp</li>\n<li>Net weight 500g</li>\n</ul>",
      short_description:
        "Twinfish Nuts Crisp is made from organically sourced nuts and processed in a high-standard hygiene-maintained facility.</p>\n<p>This is sweets type chocolate &amp; candy, it is extremely delectable for eat, which are reasonable for elderly person, grown-up, kids, woman to keep feet.</p>",
    },
    service_warranty: 0,
    service_warranty_duration_type: "Please Select",
    sell_warranty: 0,
    sell_warranty_duration_type: "Please Select",
    rating: 0,
    total_rating_count: 2,
    rating_one: 0,
    rating_two: 0,
    rating_three: 0,
    rating_four: 0,
    rating_five: 2,
    tax_value: 5,
    online_discount: {},
    campaign_member: null,
    deal_of_the_week: {},
    is_upcoming: false,
    translation: {},
    group: {
      id: 7,
      name: "Food & Groceries",
      slug: "food-grocery",
      translation: {},
      logo: "https://d2zr04sdvfux2y.cloudfront.net/test/2fbf5bae50314e5985938d30323eda42-image.svg",
    },
    store: {
      id: 3,
      slug: "k-mehr",
      name: "K Mehr",
      logo: "https://i.ibb.co/cTGfpxP/Frame-48524.jpg",
    },
    attributes: [],
    quantity_wise_price: [],
    default_country: 4,
    available_countries: [
      {
        id: 4,
        name: "Bangladesh",
        currency_code: "BDT",
        code: "BD",
        flag: "https://s3.ap-southeast-1.amazonaws.com/shob.filestorage/countryflag/bd.jpg",
      },
    ],
    minimum_order_quantity: 1,
    average_rating: 5,
  },
};

export const demoReviewData = [
  {
    id: 9,
    created_by: {
      id: 97,
      first_name: "Tasnim Tanzim Pricila",
      last_name: null,
      username: "01795232638",
      email: "tasnimtanzim55@gmail.com",
      contact_number: "01795232638",
      is_active: true,
      customer_type: "regular",
    },
    updated_by: null,
    product_variant: {
      id: 48,
      sku: "0000004843",
      name: "Nuts Crisp Candy with Mixed Flavors (500g)",
      slug: "nuts-crisp-candy-with-mixed-flavors-g-4B7A1F",
      service_warranty: 0,
      sell_warranty: 0,
      selling_price: 650,
      translation: {},
      store: {
        id: 3,
        created_at: "2024-02-16T11:23:29.602000+06:00",
        updated_at: "2024-11-25T09:42:03.454298+06:00",
        is_active: true,
        deleted_at: null,
        name: "K Mehr",
        email: "Janaalam133@dummy.com",
        type: "store",
        slug: "k-mehr",
        address:
          "Level-5(Lift-4, Ahmed Plaza, Plot#6 Road#2 Jashimuddin Ave, Dhaka 1230",
        primary_phone: "01891153770",
        secondary_phone: "01891153775",
        location: "SRID=4326;POINT (0 0)",
        map_link: "https://maps.app.goo.gl/jrkAaNwWZMg5q82L9",
        opening_time: "08:30:00",
        closing_time: "20:00:00",
        shown_in_website: false,
        off_days: ["Sunday"],
        logo: "https://i.ibb.co/cTGfpxP/Frame-48524.jpg",
        cover_photo: "https://i.ibb.co/YtVW9bs/Frame-48524-1.jpg",
        bio: "Welcome to K Mehr, where quality meets excellence.",
        about:
          'K Mehr Business Corporation is a leading business corporation specializing in premium quality goods across various categories. With a commitment to excellence and customer satisfaction, we curate a diverse range of products, ensuring the highest standards of craftsmanship and innovation. Experience sophistication and quality like never before with "K Mehr.',
        policies:
          "1. Privacy Policy\n\nOverview:\nWe value your privacy and are committed to protecting your personal information. This policy outlines how we collect, use, and safeguard your data.\n\nInformation We Collect:\n\nPersonal details (name, email, address) when you place an order.\nPayment information through secure payment processors.\nUsage data (cookies, IP address) to improve our website.\nHow We Use Your Information:\n\nTo process and fulfill your orders.\nTo communicate with you regarding your purchases.\nTo improve our services and user experience.\nData Protection:\nWe implement security measures to protect your personal information. We do not sell or share your data with third parties without your consent.\n\n2. Shipping Policy\nShipping Methods:\nWe offer various shipping options, including standard and express delivery. Please choose your preferred method at checkout.\n\nShipping Costs:\nShipping costs are calculated based on your location and the weight of your order. You will see the total shipping cost during checkout.\n\nDelivery Times:\n\nStandard shipping: 5-7 business days.\nExpress shipping: 2-3 business days.\nInternational Shipping:\nWe ship to select international locations. Additional customs fees may apply.\n\n3. Return and Refund Policy\nReturns:\nIf you’re not satisfied with your purchase, you can return items within 5 days of receipt. Items must be unused and in their original packaging.\n\nReturn Process:\n\nContact our customer service to initiate a return.\nShip the item back to us with the provided return label.\nRefunds:\nOnce we receive your return, we will process your refund according to our refund timeline. Refunds will be issued to the original payment method.\n\n4. Terms and Conditions\nAcceptance of Terms:\nBy using our website, you agree to comply with these terms. If you do not agree, please do not use our site.\n\nAccount Responsibility:\nYou are responsible for maintaining the confidentiality of your account information and for all activities that occur under your account.\n\nProduct Information:\nWe strive to provide accurate product descriptions and images. However, we do not guarantee that all information is error-free.\n\nLimitation of Liability:\nWe are not liable for any indirect, incidental, or consequential damages arising from the use of our products or services.",
        created_by: 43,
        updated_by: 153,
        store_category: [6, 26, 28],
      },
      images:
        "https://d2zr04sdvfux2y.cloudfront.net/test/304c876d36e642ef92fbb6617509d628-image.jpg",
    },
    created_at: "2024-10-05T12:52:38.783868+06:00",
    updated_at: "2024-10-05T12:52:38.783893+06:00",
    is_active: true,
    deleted_at: null,
    review: "nice",
    rating: 5,
    images: [
      "https://d2zr04sdvfux2y.cloudfront.net/test/fba5d58de05d4e91a9b775c3a6db5861-hugeicons_user-settings-01.png",
    ],
    is_accepted: true,
    order: 453,
  },
  {
    id: 7,
    created_by: {
      id: 97,
      first_name: "Tasnim Tanzim Pricila",
      last_name: null,
      username: "01795232638",
      email: "tasnimtanzim55@gmail.com",
      contact_number: "01795232638",
      is_active: true,
      customer_type: "regular",
    },
    updated_by: null,
    product_variant: {
      id: 48,
      sku: "0000004843",
      name: "Nuts Crisp Candy with Mixed Flavors (500g)",
      slug: "nuts-crisp-candy-with-mixed-flavors-g-4B7A1F",
      service_warranty: 0,
      sell_warranty: 0,
      selling_price: 650,
      translation: {},
      store: {
        id: 3,
        created_at: "2024-02-16T11:23:29.602000+06:00",
        updated_at: "2024-11-25T09:42:03.454298+06:00",
        is_active: true,
        deleted_at: null,
        name: "K Mehr",
        email: "Janaalam133@dummy.com",
        type: "store",
        slug: "k-mehr",
        address:
          "Level-5(Lift-4, Ahmed Plaza, Plot#6 Road#2 Jashimuddin Ave, Dhaka 1230",
        primary_phone: "01891153770",
        secondary_phone: "01891153775",
        location: "SRID=4326;POINT (0 0)",
        map_link: "https://maps.app.goo.gl/jrkAaNwWZMg5q82L9",
        opening_time: "08:30:00",
        closing_time: "20:00:00",
        shown_in_website: false,
        off_days: ["Sunday"],
        logo: "https://i.ibb.co/cTGfpxP/Frame-48524.jpg",
        cover_photo: "https://i.ibb.co/YtVW9bs/Frame-48524-1.jpg",
        bio: "Welcome to K Mehr, where quality meets excellence.",
        about:
          'K Mehr Business Corporation is a leading business corporation specializing in premium quality goods across various categories. With a commitment to excellence and customer satisfaction, we curate a diverse range of products, ensuring the highest standards of craftsmanship and innovation. Experience sophistication and quality like never before with "K Mehr.',
        policies:
          "1. Privacy Policy\n\nOverview:\nWe value your privacy and are committed to protecting your personal information. This policy outlines how we collect, use, and safeguard your data.\n\nInformation We Collect:\n\nPersonal details (name, email, address) when you place an order.\nPayment information through secure payment processors.\nUsage data (cookies, IP address) to improve our website.\nHow We Use Your Information:\n\nTo process and fulfill your orders.\nTo communicate with you regarding your purchases.\nTo improve our services and user experience.\nData Protection:\nWe implement security measures to protect your personal information. We do not sell or share your data with third parties without your consent.\n\n2. Shipping Policy\nShipping Methods:\nWe offer various shipping options, including standard and express delivery. Please choose your preferred method at checkout.\n\nShipping Costs:\nShipping costs are calculated based on your location and the weight of your order. You will see the total shipping cost during checkout.\n\nDelivery Times:\n\nStandard shipping: 5-7 business days.\nExpress shipping: 2-3 business days.\nInternational Shipping:\nWe ship to select international locations. Additional customs fees may apply.\n\n3. Return and Refund Policy\nReturns:\nIf you’re not satisfied with your purchase, you can return items within 5 days of receipt. Items must be unused and in their original packaging.\n\nReturn Process:\n\nContact our customer service to initiate a return.\nShip the item back to us with the provided return label.\nRefunds:\nOnce we receive your return, we will process your refund according to our refund timeline. Refunds will be issued to the original payment method.\n\n4. Terms and Conditions\nAcceptance of Terms:\nBy using our website, you agree to comply with these terms. If you do not agree, please do not use our site.\n\nAccount Responsibility:\nYou are responsible for maintaining the confidentiality of your account information and for all activities that occur under your account.\n\nProduct Information:\nWe strive to provide accurate product descriptions and images. However, we do not guarantee that all information is error-free.\n\nLimitation of Liability:\nWe are not liable for any indirect, incidental, or consequential damages arising from the use of our products or services.",
        created_by: 43,
        updated_by: 153,
        store_category: [6, 26, 28],
      },
      images:
        "https://d2zr04sdvfux2y.cloudfront.net/test/304c876d36e642ef92fbb6617509d628-image.jpg",
    },
    created_at: "2024-08-20T16:30:59.751000+06:00",
    updated_at: "2024-08-20T16:30:59.751000+06:00",
    is_active: true,
    deleted_at: null,
    review: "Quick delivery, best service!",
    rating: 5,
    images: [
      "https://d2zr04sdvfux2y.cloudfront.net/test/316bad5685e64a84af8f23f70b428fb1-WhatsApp Image 2024-08-20 at 4.28.44 PM.jpeg",
    ],
    is_accepted: true,
    order: 429,
  },
];
