export const products = [
  {
    id: 1,
    productImage: "/images/home/demo_product_img.png",
    productName: "Purifying Neem Facewash",
    price: 5555,
    discountPrice: 1324,
    isShowDiscountPrice: true,
    star: 3.0,
    isDiscountBanner: true,
    discount: 20,
  },
  {
    id: 2,
    productImage: "/images/home/demo_product_img_2.png",
    productName: "Purifying Neem Facewash",
    price: 5555,
    discountPrice: 1324,
    isShowDiscountPrice: true,
    star: 3.0,
  },
  {
    id: 3,
    productImage: "/images/home/demo_product_img.png",
    productName: "Purifying Neem Facewash",
    price: 5555,
    discountPrice: 1324,
    isShowDiscountPrice: true,
    star: 3.0,
  },
  {
    id: 4,
    productImage: "/images/home/demo_product_img_2.png",
    productName: "Purifying Neem Facewash",
    price: 5555,
    discountPrice: 1324,
    isShowDiscountPrice: true,
    star: 3.0,
  },
  {
    id: 5,
    productImage: "/images/home/demo_product_img.png",
    productName: "Purifying Neem Facewash",
    price: 5555,
    discountPrice: 1324,
    isShowDiscountPrice: true,
    star: 3.0,
  },
  {
    id: 6,
    productImage: "/images/home/demo_product_img.png",
    productName: "Purifying Neem Facewash",
    price: 5555,
    discountPrice: 1324,
    isShowDiscountPrice: true,
    star: 3.0,
  },
  {
    id: 7,
    productImage: "/images/home/demo_product_img.png",
    productName: "Purifying Neem Facewash",
    price: 5555,
    discountPrice: 1324,
    isShowDiscountPrice: true,
    star: 3.0,
  },
];

export const popularProducts = [
  {
    id: 1,
    productImage: "/images/home/demo_product_img.png",
    productName: "Purifying Neem Facewash",
    price: 5555,
    discountPrice: 1324,
    isShowDiscountPrice: true,
    star: 3.0,
    isDiscountBanner: true,
    discount: 20,
  },
  {
    id: 2,
    productImage: "/images/home/demo_product_img_2.png",
    productName: "Purifying Neem Facewash",
    price: 5555,
    discountPrice: 1324,
    isShowDiscountPrice: true,
    star: 3.0,
    isDiscountBanner: true,
    discount: 20,
  },
  {
    id: 3,
    productImage: "/images/home/demo_product_img.png",
    productName: "Purifying Neem Facewash",
    price: 5555,
    discountPrice: 1324,
    isShowDiscountPrice: true,
    star: 3.0,
    isDiscountBanner: true,
    discount: 20,
  },
  {
    id: 4,
    productImage: "/images/home/demo_product_img_2.png",
    productName: "Purifying Neem Facewash",
    price: 5555,
    discountPrice: 1324,
    isShowDiscountPrice: true,
    star: 3.0,
    isDiscountBanner: true,
    discount: 20,
  },
  {
    id: 5,
    productImage: "/images/home/demo_product_img.png",
    productName: "Purifying Neem Facewash",
    price: 5555,
    discountPrice: 1324,
    isShowDiscountPrice: true,
    star: 3.0,
    isDiscountBanner: true,
    discount: 20,
  },
];
